queue_rules:
  - name: default
    queue_conditions:
      - check-success = pre-commit.ci - pr
    merge_conditions:
      - check-success = pre-commit.ci - pr
      - check-success = x86_64-sequencing-base / build-test-upload
      - check-success = aarch64-sequencing-base / build-test-upload
      - check-success = x86_64-rnaseq / build-test-upload
      - check-success = aarch64-rnaseq / build-test-upload
      - check-success = x86_64-singlecell / build-test-upload
      - check-success = aarch64-singlecell / build-test-upload
      - check-success = x86_64-spatial / build-test-upload
      - check-success = aarch64-spatial / build-test-upload
      - check-success = x86_64-multiomics / build-test-upload
      - check-success = aarch64-multiomics / build-test-upload
      - check-success=tag-push (multiomics-notebook, default) / tag-push
      - check-success=tag-push (rnaseq-notebook, default) / tag-push
      - check-success=tag-push (sequencing-base-notebook, default) / tag-push
      - check-success=tag-push (singlecell-notebook, default) / tag-push
      - check-success=tag-push (spatial-notebook, default) / tag-push
      - check-success = wiki-update / wiki-update
    branch_protection_injection_mode: none
    merge_bot_account: huchlab-bot
    batch_size: 3
merge_queue:
  max_parallel_checks: 6
