queue_rules:
  - name: default
    queue_conditions:
      - check-success = pre-commit.ci - pr
    merge_conditions:
      - check-success = pre-commit.ci - pr
      # If any docs-triggering files changed, require build-docs check; otherwise skip it
      - or:
          # Skip build-docs check if no docs-triggering files changed
          - and:
              - -files~=^\.github/workflows/sphinx\.yml$
              - -files=Makefile
              - -files~=^docs/
              - -files=README.md
              - -files=CHANGELOG.md
              - -files=tagging/manifests/apt_packages.py
              - -files=tagging/manifests/manifest_interface.py
              - -files=tagging/taggers/sha.py
              - -files=tagging/taggers/tagger_interface.py
          # build-docs check passed
          - check-success = build-docs
      # If any build-triggering files changed, require all build checks; otherwise no build checks needed
      - or:
          # Skip build checks if no build-triggering files changed
          - and:
              - -files~=^\.github/workflows/docker\.yml$
              - -files~=^\.github/workflows/docker-build-upload\.yml$
              - -files~=^\.github/workflows/docker-test\.yml$
              - -files~=^\.github/workflows/docker-tag-push\.yml$
              - -files~=^\.github/workflows/docker-apptainer-push\.yml$
              - -files~=^\.github/workflows/docker-wiki-update\.yml$
              - -files~=^\.github/actions/apply-single-tags/action\.yml$
              - -files~=^\.github/actions/create-dev-env/action\.yml$
              - -files~=^\.github/actions/load-image/action\.yml$
              - -files~=^\.github/apptainer/
              - or:
                  - -files~=^images/
                  - and:
                      - files~=^images/.*README\.md$
                      - -files~=^images/(?!.*README\.md$).*
              - or:
                  - -files~=^tagging/
                  - and:
                      - files~=^tagging/.*README\.md$
                      - -files~=^tagging/(?!.*README\.md$).*
              - or:
                  - -files~=^tests/
                  - and:
                      - files~=^tests/.*README\.md$
                      - -files~=^tests/(?!.*README\.md$).*
              - -files~=^wiki/
              - -files=requirements-dev.txt
          # Build checks passed
          - and:
              - check-success = x86_64-datascience / build-upload
              - check-success = aarch64-datascience / build-upload
              - check-success = x86_64-sequencing-base / build-upload
              - check-success = aarch64-sequencing-base / build-upload
              - check-success = x86_64-rnaseq / build-upload
              - check-success = aarch64-rnaseq / build-upload
              - check-success = x86_64-singlecell / build-upload
              - check-success = aarch64-singlecell / build-upload
              - check-success = x86_64-spatial / build-upload
              - check-success = aarch64-spatial / build-upload
              - check-success = x86_64-multiomics / build-upload
              - check-success = aarch64-multiomics / build-upload
              - check-success = test-x86_64-datascience / test
              - check-success = test-aarch64-datascience / test
              - check-success = test-x86_64-sequencing-base / test
              - check-success = test-aarch64-sequencing-base / test
              - check-success = test-x86_64-rnaseq / test
              - check-success = test-aarch64-rnaseq / test
              - check-success = test-x86_64-singlecell / test
              - check-success = test-aarch64-singlecell / test
              - check-success = test-x86_64-spatial / test
              - check-success = test-aarch64-spatial / test
              - check-success = test-x86_64-multiomics / test
              - check-success = test-aarch64-multiomics / test
              - check-success = tag-push (datascience-notebook, default) / tag-push
              - check-success = tag-push (multiomics-notebook, default) / tag-push
              - check-success = tag-push (rnaseq-notebook, default) / tag-push
              - check-success = tag-push (sequencing-base-notebook, default) / tag-push
              - check-success = tag-push (singlecell-notebook, default) / tag-push
              - check-success = tag-push (spatial-notebook, default) / tag-push
              - check-success = apptainer-push (datascience-notebook, default) / apptainer-push
              - check-success = apptainer-push (sequencing-base-notebook, default) / apptainer-push
              - check-success = apptainer-push (rnaseq-notebook, default) / apptainer-push
              - check-success = apptainer-push (singlecell-notebook, default) / apptainer-push
              - check-success = apptainer-push (multiomics-notebook, default) / apptainer-push
              - check-success = apptainer-push (spatial-notebook, default) / apptainer-push
              - check-success = wiki-update / wiki-update
    branch_protection_injection_mode: none
    merge_bot_account: huchlab-bot
    batch_size: 3
merge_queue:
  max_parallel_checks: 6
pull_request_rules:
  - name: Label conflicting pull requests
    description: Add a label to a pull request with conflict to spot it easily
    conditions:
      - conflict
      - -closed
    actions:
      label:
        toggle:
          - conflict
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position >= 0
    actions:
      label:
        toggle:
          - merge-queued
