name: Copy and tag image directly from GHCR to Registry
description: Copy the image directly from GHCR to Registry without pulling to local disk

inputs:
  image:
    description: Image name
    required: true
  platform:
    description: Image platform
    required: true
  variant:
    description: Variant tag prefix
    required: true

runs:
  using: composite
  steps:
    - name: Download tags file 📥
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        name: ${{ inputs.image }}-${{ inputs.platform }}-${{ inputs.variant }}-tags
        path: /tmp/jupyter/tags/

    - name: Login to GHCR 🔐
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
      id: login-ghcr

    - name: Install Crane
      uses: imjasonh/setup-crane@v0.5

    - name: Remote Tagging with Crane
      run: |
        SOURCE_IMAGE="ghcr.io/${{ github.repository_owner }}/sequencing-docker-stacks/${{ inputs.image }}:build-${{ github.sha }}-${{ github.run_id }}-${{ inputs.platform }}-${{ inputs.variant }}"
        DEST_REPO="${{ env.REGISTRY }}/${{ env.OWNER }}/${{ inputs.image }}"
        TAG_FILE="/tmp/jupyter/tags/${{ inputs.image }}-${{ inputs.platform }}-${{ inputs.variant }}-tags"

        # Perform ONE actual copy to the destination registry
        # This moves the layers once.
        FIRST_TAG=$(head -n 1 "$TAG_FILE")
        echo "Initial move of layers to $DEST_REPO:$FIRST_TAG"
        crane copy "$SOURCE_IMAGE" "$DEST_REPO:$FIRST_TAG"

        # Use 'crane tag' for all subsequent tags
        # This is an instant API call with no data transfer.
        while IFS= read -r tag; do
          if [ "$tag" != "$FIRST_TAG" ]; then
            echo "Fast-tagging $tag..."
            crane tag "$DEST_REPO:$FIRST_TAG" "$tag"
          fi
        done < "$TAG_FILE"
      shell: bash

    - name: Install Syft 📦
      uses: anchore/sbom-action/download-syft@28d71544de8eaf1b958d335707167c5f783590ad # v0.22.2
      id: syft

    - name: Generate SBOM for the image 🧾
      run: |
        syft \
          --from oci-registry \
          --platform linux/${{ inputs.platform == 'aarch64' && 'arm64' || 'amd64' }} \
          -o spdx-json=/tmp/sbom-${{ inputs.image }}-${{ inputs.platform }}-${{ inputs.variant }}.spdx.json \
          ghcr.io/${{ github.repository_owner }}/sequencing-docker-stacks/${{ inputs.image }}:build-${{ github.sha }}-${{ github.run_id }}-${{ inputs.platform }}-${{ inputs.variant }}
      shell: bash

    - name: Upload SBOM artifact 📤
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ inputs.image }}-${{ inputs.platform }}-${{ inputs.variant }}-sbom.spdx.json
        path: /tmp/sbom-${{ inputs.image }}-${{ inputs.platform }}-${{ inputs.variant }}.spdx.json
        retention-days: 40
