# GitHub Copilot Reference Configuration for Sequencing Docker Stacks

# This configuration serves as a reference for contributors working with
# GitHub Copilot and other AI assistants on this repository.
# It documents the repository's structure, conventions, and preferences.

# Note: This is a project-specific documentation file and not part of the
# official GitHub Copilot API. Use it as a reference when working with
# AI coding assistants to ensure suggestions align with project conventions.

version: 1

# Repository context
repository:
  name: sequencing-docker-stacks
  owner: huchlab
  description: Ready-to-run Docker images tailored for sequencing data analysis

# Primary languages and frameworks
languages:
  - python
  - r
  - dockerfile
  - bash
  - yaml
  - markdown

# Key technologies
technologies:
  - docker
  - jupyter
  - bioconductor
  - conda
  - pytest
  - sphinx
  - github-actions

# Code style preferences
style:
  python:
    formatter: black
    linter: flake8
    line_length: 88
  dockerfile:
    linter: hadolint
  markdown:
    linter: markdownlint

# Testing framework
testing:
  framework: pytest
  location: tests/
  run_command: "make test/<image-name>"

# Documentation
documentation:
  tool: sphinx
  location: docs/
  build_command: "make docs"
  format: rst

# Build system
build:
  tool: make
  dockerfile_location: images/
  build_command: "make build/<image-name>"

# Conventions
conventions:
  commit_style: conventional
  branch_naming: feature/, bugfix/, hotfix/
  pr_template: .github/pull_request_template.md

# Important directories
directories:
  source: images/
  tests: tests/
  docs: docs/
  workflows: .github/workflows/
  examples: examples/
