name: Load Docker image
description: Pull the image from GHCR and tag it for local use

inputs:
  image:
    description: Image name
    required: true
  platform:
    description: Image platform
    required: true
  variant:
    description: Variant tag prefix
    required: true

runs:
  using: composite
  steps:
    - name: Get commit SHA
      id: get_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Login to GHCR 🔐
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Pull image from GHCR 📥
      run: |
        PLATFORM="${{ inputs.platform }}"
        # Convert platform names: x86_64 -> amd64, aarch64 -> arm64
        if [ "$PLATFORM" = "x86_64" ]; then
          DOCKER_PLATFORM="linux/amd64"
        elif [ "$PLATFORM" = "aarch64" ]; then
          DOCKER_PLATFORM="linux/arm64"
        else
          DOCKER_PLATFORM="linux/$PLATFORM"
        fi

        docker pull --platform "$DOCKER_PLATFORM" ghcr.io/${{ github.repository_owner }}/sequencing-docker-stacks/${{ inputs.image }}:build-${{ steps.get_sha.outputs.sha }}-${{ github.run_id }}-${{ inputs.platform }}-${{ inputs.variant }}
      shell: bash

    - name: Tag image for local use 🏷
      run: |
        docker tag \
          ghcr.io/${{ github.repository_owner }}/sequencing-docker-stacks/${{ inputs.image }}:build-${{ steps.get_sha.outputs.sha }}-${{ github.run_id }}-${{ inputs.platform }}-${{ inputs.variant }} \
          quay.io/${{ github.repository_owner }}/${{ inputs.image }}
      shell: bash

    - name: Logout from GHCR 🔐
      if: always()
      run: |
        docker logout ghcr.io
      shell: bash

    - name: Show Docker images 📦
      run: docker image ls --all
      shell: bash
