name: Download a Docker image and its tags from GitHub artifacts, apply them, and push the image to the Registry

env:
  REGISTRY: quay.io
  OWNER: ${{ github.repository_owner }}
  PUSH_TO_REGISTRY: ${{ github.repository_owner == 'huchlab' && (github.ref == 'refs/heads/main' || github.event_name == 'schedule') }}

on:
  workflow_call:
    inputs:
      image:
        description: Image name
        required: true
        type: string
      variant:
        description: Variant tag prefix
        required: true
        type: string
      timeout-minutes:
        description: Timeout in minutes
        default: 45
        type: number
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_TOKEN:
        required: true

permissions:
  contents: read
  packages: read

jobs:
  tag-push:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}

    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Create dev environment 📦
        uses: ./.github/actions/create-dev-env

      - name: Login to Registry 🔐
        if: env.PUSH_TO_REGISTRY == 'true'
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
        id: login

      - name: Login to GHCR 🔐
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
        id: login-ghcr

      - name: Copy aarch64 image and apply tags directly 🏷
        uses: ./.github/actions/copy-and-tag-image
        with:
          image: ${{ inputs.image }}
          variant: ${{ inputs.variant }}
          platform: aarch64

      - name: Copy x86_64 image and apply tags directly 🏷
        uses: ./.github/actions/copy-and-tag-image
        with:
          image: ${{ inputs.image }}
          variant: ${{ inputs.variant }}
          platform: x86_64

      - name: Merge tags for the images 🔀
        run: |
          python3 -m tagging.apps.merge_tags \
            --image ${{ inputs.image }} \
            --variant ${{ inputs.variant }} \
            --tags-dir /tmp/jupyter/tags/
        shell: bash

      - name: Logout from Registry 🔐
        if: always()
        run: |
          docker logout ${{ env.REGISTRY }}
        shell: bash

      - name: Logout from GHCR 🔐
        if: always()
        run: |
          docker logout ghcr.io
        shell: bash
